com.is1.proyecto.models.Materia:default
com.is1.proyecto.models.Alumno:default
com.is1.proyecto.models.Profesor:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.Inscripcion:default
com.is1.proyecto.models.PlanDeEstudio:default
com.is1.proyecto.models.Carrera:default
